services: 
  broker:
    image: eclipse-mosquitto:2.0.20
    container_name: broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - recam_network
  knowledge:
    image: influxdb:2.7.10
    container_name: knowledge
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=recam123
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=token
      - DOCKER_INFLUXDB_INIT_ORG=RECAM
      - DOCKER_INFLUXDB_INIT_BUCKET=RECAM
    volumes:
      - knowledge_v:/var/lib/influxdb2
    networks:
      - recam_network

  monitor:
    image: telegraf:1.32.3
    container_name: monitor
    depends_on:
      - broker
      - knowledge
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - recam_network

  sensors:
    build:
      context: ./sensors
    container_name: sensors
    environment:
      - BROKER=broker  # Service name in docker-compose.yml
      - PORT=1883
      - STEP_DURATION=1
      - SECONDS_IN_A_SIMULATION_STEP=60
      - TAU_DELTA_INTERVAL_BOUNDS=60,90
    depends_on:
      - broker
      - knowledge
      - monitor
    networks:
      - recam_network
    volumes:
      - ./recam-config:/app/config
    ports:
      - "5001:5000"
  analyzer:
    build:
      context: ./analyzer
    container_name: analyzer
    environment:
      - INFLUXDB_URL=http://knowledge:8086
      - INFLUXDB_TOKEN=token
      - INFLUXDB_ORG=RECAM
      - INFLUXDB_BUCKET=RECAM
      - PLANNER_API=http://planner:8080
    depends_on:
      - sensors
    networks:
      - recam_network
    volumes:
      - ./recam-config:/app/config

  planner:
    build:
      context: ./planner
    container_name: planner
    environment:
      - BROKER=broker 
      - PORT=1883
    depends_on:
      - analyzer
    networks:
      - recam_network
    volumes:
      - ./recam-config:/app/config
  
  executor:
    build:
      context: ./executor
    container_name: executor
    environment:
      - BROKER=broker 
      - PORT=1883
    depends_on:
      - planner
    networks:
      - recam_network
    volumes:
      - ./recam-config:/app/config

  actuators:
    build:
      context: ./actuators
    container_name: actuators
    environment:
      - BROKER=broker 
      - PORT=1883
    depends_on:
      - executor
    networks:
      - recam_network
    volumes:
      - ./recam-config:/app/config

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    depends_on:
      - knowledge
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=recam123
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - recam_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go-backend
    depends_on:
      - knowledge
    ports:
      - "8080:8080"
    networks:
      - recam_network
    environment:
      - PORT=8080
      - FRONTEND_URL=http://frontend:4000
      - INFLUXDB_URL=http://knowledge:8086
      - INFLUXDB_TOKEN=token
      - INFLUXDB_ORG=RECAM
      - INFLUXDB_BUCKET=RECAM
      - SENSORS_API=http://sensors:5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "4000:80"
    networks:
      - recam_network
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080


volumes:
  knowledge_v: 
    name: knowledge_v

networks:
  recam_network: